---
title: "Learnr Test"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}

# Import required libraries
library(learnr)
library(dplyr)
library(tidyr)
library(purrr)
library(googlesheets4)

# Set tutorial options
tutorial_options(exercise.eval = FALSE)

# Initialize an empty data frame
df <- data.frame(
  user_id = character(),
  problem = character(),
  points = integer(),
  answer = character(), 
  correct = logical(),
  question_num = character(),
  stringsAsFactors = FALSE  # Prevent strings being converted to factors
)

# Function to record tutorial events
event_recorder <- function(tutorial_id, tutorial_version, user_id, event, data) {
  
  # Check if event is exercise_submission or question_submission
  if (event %in% c("exercise_submission", "question_submission")) {
    
    # Extract question number from the question
    question_num <- ifelse(grepl("\\[Question \\d+\\]", data$question), 
                           gsub(".*\\[Question (\\d+)\\].*", "\\1", data$question), NA)
    
    # Extract points from the question
    points <- ifelse(grepl("\\[Points: \\d+\\]", data$question), 
                     as.integer(gsub(".*\\[Points: (\\d+)\\].*", "\\1", data$question)), 1)
    
    # Extract problem without [Question X] and [Points: X]
    problem <- gsub("\\[Question \\d+\\]|\\[Points: \\d+\\]", "", data$question)
    
    # Check if there's already a row with the same user_id and question_num
    previous_rows <- df[df$user_id == user_id & gsub("_.*", "", df$question_num) == paste0("Q", question_num), ]
    if (nrow(previous_rows) > 0) {
      attempt_num <- max(as.numeric(gsub(".*_(\\d+)$", "\\1", previous_rows$question_num))) + 1
    } else {
      attempt_num <- 1
    }
    
    # Create new row with event data
    new_row <- data.frame(
      user_id = user_id,
      problem = problem,  # use the new problem variable here
      points = points,
      answer = data$answer, 
      correct = ifelse(data$correct, TRUE, FALSE),
      question_num = paste0("Q", question_num, ".", attempt_num),  # Add "Q" before the question number and "_attempt_num"
      stringsAsFactors = FALSE  # Prevent strings being converted to factors
    )

    # Append new row to global data frame only if the data's question is not "Submit Assignment?"
    if(data$question != "Submit Assignment?") {
      df <<- rbind(df, new_row)
    }

    # If it's the final question, reshape and write data frame to Google Sheets
    if(data$question == "Submit Assignment?") {
      
      # Reshape data frame to long format
      df_long <- df %>% 
        gather(key = "key", value = "value", -user_id, -question_num)
        
      # Pivot the data frame back to wide format
      df_wide <- df_long %>% 
        pivot_wider(names_from = c("question_num", "key"), names_sep = "_", values_from = "value")
      
      # Generate the column order
      unique_questions <- sort(unique(df$question_num))
      col_order <- c("user_id", unlist(lapply(unique_questions, function(i) paste0(i, c("_problem", "_answer", "_correct", "_points")))))
      
      # Reorder the columns
      df_wide <- df_wide[, col_order]

      # Create a new Google Sheet and write the data frame to it
      ss <- gs4_create(name = "logfile")
      sheet_write(df_wide, ss = ss, sheet = "Sheet1")
    }
  }
}



# Set the global option to use our event recorder function
options(tutorial.event_recorder = event_recorder)

# Set knitr options
knitr::opts_chunk$set(echo = FALSE)

```

```{r multiplechoice}

question(
  "[Question 1] [Points: 1] How long did it take Camden to troubleshoot this when first setting it up?",
  answer("30 Minutes"),
  answer("1 Hour", correct = TRUE),
  answer("1.5 Hours"),
  answer("2 Hours")
)
```

```{r numeric}

question_numeric(
"[Question 2] [Points: 2] What is pi rounded to 2 decimal points?",
 answer(3, message = "Don't forget to use the decimals argument"),
 answer(3.1, message = "Too few decimals"),
 answer(3.142, message = "Too many decimals"),
 answer(3.14, correct = TRUE),
 allow_retry = TRUE,
 min = 3,
 max = 4,
 step = 0.01
)
```

```{r toltest}

question_numeric(
  "[Question 3] [Points: 5] What is the approximate population of Mount Vernon?",
  answer(4460, correct = TRUE, message = "As of 2021, the population of Mount Vernon is 4460."),
  tolerance = 100,
  step = 10,
  options = list(
    placeholder = "Hint: The answer is between 4,000 and 5,000"
  )
)
```

```{r imagetest}
question(
  "[Question 4] [Points: 1] Which one of these arrows is facing left?",
  answer(
    htmltools::img(src = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Small_arrow_pointing_left.svg/440px-Small_arrow_pointing_left.svg.png"), correct = TRUE),
  answer(
    htmltools::img(src = "https://cdn-icons-png.flaticon.com/512/66/66831.png")),
  answer(htmltools::img(src = "https://w7.pngwing.com/pngs/821/97/png-transparent-black-arrow-up-illustration-arrow-desktop-symbol-up-arrow-angle-triangle-sign-thumbnail.png")),
  answer(htmltools::img(src = "https://png.pngtree.com/png-vector/20190419/ourmid/pngtree-vector-down-arrow-icon-png-image_956433.jpg")),
  allow_retry = TRUE,
  random_answer_order = TRUE
  
)
```

```{r submission}
question("Submit Assignment?",
         answer("Yes", correct = TRUE)
         )
```